[15.0][MIG] email_from
Nitrokey/odoo-modules pull request #102
Opened 2022-09-28 06:22 UTC by nikunjantala

2022-09-30 12:14 UTC, manengel commented
@nikunjantala @jans23 I had a very short look on that module and, well: The module is confusing me. On Odoo such things are normally handed on a per-template basis. You can go to Settings -> Technical -> [in section E-Mail] to Templates and change things like the (default) sender, the model.

So....is this module really a benefit you knowingly want to have or did you just bypass the standard of Odoo without being aware of it?

2022-09-30 12:23 UTC, jans23 commented
The idea is to use this module once instead of changing each template.

2022-09-30 12:47 UTC, manengel commented
@jans23 Ah O.K., I will then do the review as requested.

2022-09-30 15:19 UTC, manengel requested changes
I commented a few small things. Just let a formatter do the job and you are good to go! It was hard to test this, but I will report about that at a better suited place. The module itself works technically fine! +1

2022-09-30 15:19 UTC, manengel commented on email_from/views/res_config_settings_views.xml
> +                            </div>
The formatting looks really strange to me.

2022-09-30 15:19 UTC, manengel commented on email_from/views/email_from.xml
> +                    </group>
Formatting.

2022-10-03 09:18 UTC, nileshsheliya commented on email_from/views/res_config_settings_views.xml
> +                            </div>
Its auto formatting by pre-commit command. If we not format it and push it git, pipeline will failed.

2022-10-05 11:44 UTC, manengel commented on email_from/views/res_config_settings_views.xml
> +                            </div>
O.K. then I did not say a thing.

2022-10-05 11:44 UTC, manengel approved these changes

2022-10-05 11:45 UTC, merged