[ADD] add module email_restrict_autoreply
Nitrokey/odoo-modules pull request #112
Opened 2022-12-21 11:54 UTC by dsolanki-initos

2022-12-22 19:33 UTC, alihashaam commented on email_restrict_autoreply/__init__.py
> +from . import models
CI issue. No new line at the end of the file

2022-12-22 19:35 UTC, alihashaam requested changes

2022-12-22 19:35 UTC, alihashaam commented on email_restrict_autoreply/models/__init__.py
> +from . import purchase
CI issue. No new line at the end of the file

2022-12-22 19:35 UTC, alihashaam commented on email_restrict_autoreply/models/purchase.py
> +        partners = [(partner) for partner in rdata.get('partners') if partner_obj.browse(partner.get('id')) and partner_obj.browse(partner.get('id')).email in IncomingMails.mapped('user')]
CI issue. Line too long

2022-12-22 19:35 UTC, alihashaam commented on email_restrict_autoreply/models/purchase.py
> +                           model_description=model_description, mail_auto_delete=mail_auto_delete)
CI issue. No new line at the end of the file

2022-12-22 19:35 UTC, alihashaam commented on email_restrict_autoreply/__manifest__.py
> +}
CI issue. No new line at the end of the file

2022-12-22 19:37 UTC, alihashaam commented
@dsolanki-initos 

Can you please fix the CI issues and please add ticket number in comments as it makes it easy to navigate. 

@jans23 I assigned the PR to myself

2022-12-22 19:39 UTC, alihashaam requested changes
Changes requested

2022-12-26 05:47 UTC, dsolanki-initos commented
@alihashaam, I've fixed the CI issues as per your feedback.

2023-01-06 10:38 UTC, merged