[MIG] chatter_confirm_message: Migration to 15.0
Nitrokey/odoo-modules pull request #93
Opened 2022-07-06 06:56 UTC by nikunjantala

2022-07-08 08:13 UTC, jans23 commented
Fix the failed checks please.

2022-07-25 07:05 UTC, jans23 commented
Fix the CI checks.

2022-08-06 05:57 UTC, jans23 commented
Resolve the conflicts please

2022-09-05 07:40 UTC, nileshsheliya commented
@jans23 Merge conflict is fixed.

2022-10-05 14:03 UTC, manengel requested changes
Something seems to be very wrong with the JavaScript. I invited an external partner (with no user account) to be a follower and it rendered my Odoo instance unusable. I do not get any errors, but attempting to load anything in that Odoo instance does now lead to a white screen. In the console output of Odoo, there is no error, though. In the debugging console of the browser, I got that big error message: 
![Bildschirmfoto vom 2022-10-05 16-01-14](https://user-images.githubus
![Bildschirmfoto vom 2022-10-05 16-02-22](https://user-images.githubusercontent.com/55840951/194079998-c0ad4770-9876-4b08-b52d-dc2f4803a921.png)
![Bildschirmfoto vom 2022-10-05 16-02-39](https://user-images.githubusercontent.com/55840951/194080011-51145abd-1d0b-4895-8623-7fad0191b999.png)

ercontent.com/55840951/194079980-1894dfad-0aae-42ff-b4ad-214630e402ba.png)

2022-10-05 14:03 UTC, manengel commented on chatter_confirm_message/static/description/index.html
> +<?xml version="1.0" encoding="utf-8" ?>
Is this file required nowadays?

2022-10-05 14:03 UTC, manengel commented on configure_product/readme/DESCRIPTION.rst
> +product to the sale order and purchase order form.
Seems pretty unrelated to me, but if there was nothing more to do for that module: okay.

2022-10-08 06:38 UTC, nileshsheliya commented on chatter_confirm_message/static/description/index.html
> +<?xml version="1.0" encoding="utf-8" ?>
Issue is just because import is removed in js doing formatting of code according to standard. Now I added it and it work well.

2022-10-14 13:44 UTC, manengel approved these changes
Looks good to me now.

2022-10-14 17:15 UTC, merged