[15.0][MIG]phone_validation_e164
Nitrokey/odoo-modules pull request #94
Opened 2022-07-20 09:19 UTC by dsolanki-initos

@jans23 FYI,

2022-07-20 17:45 UTC, jans23 commented
Tests are still failing. Is this WIP?

2022-07-21 04:44 UTC, dsolanki-initos commented
> Tests are still failing. Is this WIP?

No, but tests case failed from another module

2022-09-02 13:43 UTC, manengel requested changes
I left some review feedback. Also did I try to test the module, but it did not have any visible function.

2022-09-02 13:43 UTC, manengel commented on phone_validation_e164/controllers/main.py
> +        resposnse = super(WebsiteSaleExt, self).address(**kw)
Spelling error in variable name.

2022-09-02 13:43 UTC, manengel commented on phone_validation_e164/__manifest__.py
> +    There are three types of formator 1) International 2) national and 3) E164
Hmm, maybe attempt to change this part of summary to something like this:
There are formatters for the three types of phone number formats:
1) The international format
2) The national format
3) The E164 format

2022-09-02 13:43 UTC, manengel commented on phone_validation_e164/__manifest__.py
> +    By using we have added default e164 phone formator for partner form.
"By using" what? This sentence is really hard to comprehend for me.

2022-09-02 13:43 UTC, manengel commented on phone_validation_e164/README.rst
> +By using we have added default e164 phone formator for partner form.
Same as below for the manifest file.

2022-09-02 13:45 UTC, jans23 commented on phone_validation_e164/__manifest__.py
> +    By using we have added default e164 phone formator for partner form.
Avoid redundancy and keep description in README only.

2022-09-06 12:31 UTC, manengel commented on phone_validation_e164/__manifest__.py
> +    By using we have added default e164 phone formator for partner form.
If I remember correctly, in this case, part of the README is generated out of the manifest file. (oca-gen-addon-readme) EDIT: At least, it should. Refer to #93 because there this is done correctly.

2022-09-27 13:55 UTC, manengel commented
@dsolanki-initos Do you consider your work being done here? Is this still being worked on?

2022-09-28 04:56 UTC, dsolanki-initos commented
> @dsolanki-initos Do you consider your work being done here? Is this still being worked on?

Yes I've done migration and I am not worked on it

2022-09-30 07:01 UTC, manengel reviewed
Looks much better now from my point of view, but a functional test is not possible for me right now.

2022-09-30 07:02 UTC, manengel approved these changes

2022-09-30 08:37 UTC, jans23 commented on phone_validation_e164/__manifest__.py
> +    By using we have added default e164 phone formator for partner form.
@manengel Is this resolved?

2022-09-30 08:38 UTC, jans23 commented
@dsolanki-initos Did you test it?

2022-09-30 08:42 UTC, dsolanki-initos commented
> @dsolanki-initos Did you test it?

Yes

2022-09-30 09:06 UTC, merged